{% set base_name = "libignition-msgs" %}
{% set version = "5.1.0" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-msgs/archive/ignition-msgs{{ version.split('.')[0] }}_{{ version }}.tar.gz
    sha256: 530e09a548bb1acf6b2571877992823cb2c50d0c0ea0abda7fa4ad7efdb1b82d

build:
  number: 4
  skip: true  # [win and vc<14]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]
    - make                               # [not win]
    - cmake
    - pkg-config                         # [not win]
  host:
    - libignition-math6 >=6.4
    - tinyxml2
    - protobuf
    - libprotobuf                        # [not win]
  run:
    - libignition-math6 >=6.4
    - tinyxml2
    - protobuf
    - libprotobuf                        # [not win]

test:
  commands:
    - test -f ${PREFIX}/include/ignition/msgs{{ version.split('.')[0] }}/ignition/msgs.hh  # [not win]
    - test -f ${PREFIX}/lib/libignition-msgs{{ version.split('.')[0] }}.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-msgs{{ version.split('.')[0] }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/cmake/ignition-msgs{{ version.split('.')[0] }}/ignition-msgs{{ version.split('.')[0] }}-config.cmake  # [not win]
    - if exist %PREFIX%\\Library\\include\\ignition\\msgs{{ version.split('.')[0] }}\\ignition\\msgs.hh (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\lib\\ignition-msgs{{ version.split('.')[0] }}.lib (exit 0) else (exit 1)  # [win]
    - if exist $PREFIX$\\Library\\bin\\ignition-msgs{{ version.split('.')[0] }}.dll (exit 0) else (exit 1)  # [win]
    - if exist %PREFIX%\\Library\\lib\\cmake\\ignition-msgs{{ version.split('.')[0] }}\\ignition-msgs{{ version.split('.')[0] }}-config.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://bitbucket.org/ignitionrobotics/ign-msgs
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Ignition Messages'

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
    - Tobias-Fischer
